# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '-rc3',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"u\n\x14request_vote_message\x12\x0e\n\x06nodeId\x18\x01 \x01(\x05\x12\x13\n\x0b\x63urrentTerm\x18\x02 \x01(\x05\x12\x11\n\tlogLength\x18\x03 \x01(\x05\x12\x10\n\x08lastTerm\x18\x04 \x01(\x05\x12\x13\n\x0brequestType\x18\x05 \x01(\x05\"[\n\x11reply_vote_mesage\x12\x0e\n\x06nodeId\x18\x01 \x01(\x05\x12\x13\n\x0b\x63urrentTerm\x18\x02 \x01(\x05\x12\x0e\n\x06isVote\x18\x03 \x01(\x08\x12\x11\n\treplyType\x18\x04 \x01(\x05\"\xfe\x01\n\x19request_replicate_message\x12\x10\n\x08leaderId\x18\x01 \x01(\x05\x12\x13\n\x0b\x63urrentTerm\x18\x02 \x01(\x05\x12\x14\n\x0cprefixLength\x18\x03 \x01(\x05\x12\x12\n\nprefixTerm\x18\x04 \x01(\x05\x12\x14\n\x0c\x63ommitLength\x18\x05 \x01(\x05\x12;\n\x06suffix\x18\x06 \x03(\x0b\x32+.raft.request_replicate_message.log_message\x12\x13\n\x0brequestType\x18\x07 \x01(\x05\x1a(\n\x0blog_message\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0b\n\x03mes\x18\x02 \x01(\x05\"n\n\x17reply_replicate_massage\x12\x0e\n\x06nodeId\x18\x01 \x01(\x05\x12\x13\n\x0b\x63urrentTerm\x18\x02 \x01(\x05\x12\x0b\n\x03\x61\x63k\x18\x03 \x01(\x05\x12\x0e\n\x06result\x18\x04 \x01(\x08\x12\x11\n\treplyType\x18\x05 \x01(\x05\"\x1f\n\rrequest_entry\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1d\n\x0breply_entry\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32\xce\x01\n\x04RAFT\x12\x42\n\x0bRequestVote\x12\x1a.raft.request_vote_message\x1a\x17.raft.reply_vote_mesage\x12N\n\x0cReplicateLog\x12\x1f.raft.request_replicate_message\x1a\x1d.raft.reply_replicate_massage\x12\x32\n\x08\x41\x64\x64\x45ntry\x12\x13.raft.request_entry\x1a\x11.raft.reply_entryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST_VOTE_MESSAGE']._serialized_start=20
  _globals['_REQUEST_VOTE_MESSAGE']._serialized_end=137
  _globals['_REPLY_VOTE_MESAGE']._serialized_start=139
  _globals['_REPLY_VOTE_MESAGE']._serialized_end=230
  _globals['_REQUEST_REPLICATE_MESSAGE']._serialized_start=233
  _globals['_REQUEST_REPLICATE_MESSAGE']._serialized_end=487
  _globals['_REQUEST_REPLICATE_MESSAGE_LOG_MESSAGE']._serialized_start=447
  _globals['_REQUEST_REPLICATE_MESSAGE_LOG_MESSAGE']._serialized_end=487
  _globals['_REPLY_REPLICATE_MASSAGE']._serialized_start=489
  _globals['_REPLY_REPLICATE_MASSAGE']._serialized_end=599
  _globals['_REQUEST_ENTRY']._serialized_start=601
  _globals['_REQUEST_ENTRY']._serialized_end=632
  _globals['_REPLY_ENTRY']._serialized_start=634
  _globals['_REPLY_ENTRY']._serialized_end=663
  _globals['_RAFT']._serialized_start=666
  _globals['_RAFT']._serialized_end=872
# @@protoc_insertion_point(module_scope)
